import argparse
import os
from datetime import datetime, timezone
from typing import Annotated

import psycopg
from arcade_mcp_server import MCPApp
from dotenv import find_dotenv, load_dotenv


def load_environment() -> None:
    for filename, override in ((".env", False), (".env.local", True)):
        env_path = find_dotenv(filename, usecwd=True)
        if env_path:
            load_dotenv(env_path, override=override)


load_environment()

app = MCPApp(name="deal_memory")


def database_url() -> str:
    resolved_url = os.getenv("DEAL_MEMORY_DATABASE_URL", "").strip()
    if not resolved_url:
        raise RuntimeError(
            "DEAL_MEMORY_DATABASE_URL is required for the deal memory server."
        )
    return resolved_url


def get_connection():
    return psycopg.connect(database_url())


def serialize_created_at(value: object) -> str:
    if isinstance(value, datetime):
        return value.astimezone(timezone.utc).isoformat()
    return str(value)


def init_db() -> None:
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS deal_notes (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  deal_id TEXT NOT NULL,
                  note TEXT NOT NULL,
                  tags TEXT,
                  created_at TIMESTAMPTZ NOT NULL
                )
                """
            )
            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS deal_notes_deal_id_idx
                ON deal_notes (deal_id)
                """
            )
            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS deal_notes_created_at_idx
                ON deal_notes (created_at DESC)
                """
            )


@app.tool()
def upsert_deal_note(
    deal_id: Annotated[str, "CRM deal identifier, for example D-1004"],
    note: Annotated[str, "Free-form deal note to store in memory"],
    tags: Annotated[str, "Optional comma-separated tags"] = "",
) -> dict:
    """Store a note for a deal.

    Args:
        deal_id: CRM deal identifier.
        note: Free-form note text.
        tags: Optional comma-separated tags.
    """

    init_db()
    normalized_tags = ",".join([tag.strip() for tag in tags.split(",") if tag.strip()])
    created_at = datetime.now(timezone.utc)
    created_at_value = created_at.isoformat()

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO deal_notes (deal_id, note, tags, created_at)
                VALUES (%s, %s, %s, %s)
                RETURNING id
                """,
                (deal_id, note, normalized_tags, created_at),
            )
            note_id = cursor.fetchone()[0]

    return {
        "saved": True,
        "note_id": note_id,
        "deal_id": deal_id,
        "created_at": created_at_value,
    }


@app.tool()
def get_deal_context(
    deal_id: Annotated[str, "CRM deal identifier, for example D-1004"],
    limit: Annotated[int, "Maximum number of recent notes to return"] = 5,
) -> dict:
    """Return recent notes for a deal.

    Args:
        deal_id: CRM deal identifier.
        limit: Maximum number of notes to return.
    """

    init_db()
    bounded_limit = min(max(limit, 1), 20)

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT id, note, tags, created_at
                FROM deal_notes
                WHERE deal_id = %s
                ORDER BY id DESC
                LIMIT %s
                """,
                (deal_id, bounded_limit),
            )
            rows = cursor.fetchall()

    notes = [
        {
            "id": row[0],
            "note": row[1],
            "tags": row[2] or "",
            "created_at": serialize_created_at(row[3]),
        }
        for row in rows
    ]

    return {
        "deal_id": deal_id,
        "note_count": len(notes),
        "notes": notes,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Deal memory MCP server")
    parser.add_argument(
        "transport",
        nargs="?",
        default="stdio",
        choices=["stdio", "http"],
        help="Transport to run",
    )
    parser.add_argument("--host", default="127.0.0.1", help="HTTP bind host")
    parser.add_argument("--port", type=int, default=9400, help="HTTP bind port")

    args = parser.parse_args()
    init_db()

    if args.transport == "http":
        app.run(transport="http", host=args.host, port=args.port)
        return

    app.run(transport="stdio")


if __name__ == "__main__":
    main()
